// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/student_api.proto
#ifndef GRPC_api_2fstudent_5fapi_2eproto__INCLUDED
#define GRPC_api_2fstudent_5fapi_2eproto__INCLUDED

#include "api/student_api.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace api {

class Service final {
 public:
  static constexpr char const* service_full_name() {
    return "api.Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status NewStudent(::grpc::ClientContext* context, const ::model::Student& request, ::protos::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::Result>> AsyncNewStudent(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::Result>>(AsyncNewStudentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::Result>> PrepareAsyncNewStudent(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::Result>>(PrepareAsyncNewStudentRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protos::Result>* AsyncNewStudentRaw(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protos::Result>* PrepareAsyncNewStudentRaw(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status NewStudent(::grpc::ClientContext* context, const ::model::Student& request, ::protos::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::Result>> AsyncNewStudent(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::Result>>(AsyncNewStudentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::Result>> PrepareAsyncNewStudent(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::Result>>(PrepareAsyncNewStudentRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::protos::Result>* AsyncNewStudentRaw(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protos::Result>* PrepareAsyncNewStudentRaw(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_NewStudent_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status NewStudent(::grpc::ServerContext* context, const ::model::Student* request, ::protos::Result* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_NewStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NewStudent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_NewStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewStudent(::grpc::ServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewStudent(::grpc::ServerContext* context, ::model::Student* request, ::grpc::ServerAsyncResponseWriter< ::protos::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_NewStudent<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_NewStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_NewStudent() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::model::Student, ::protos::Result>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::model::Student* request, ::protos::Result* response) { return this->NewStudent(context, request, response); }));}
    void SetMessageAllocatorFor_NewStudent(
        ::grpc::experimental::MessageAllocator< ::model::Student, ::protos::Result>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::model::Student, ::protos::Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_NewStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewStudent(::grpc::ServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NewStudent(
      ::grpc::CallbackServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NewStudent(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_NewStudent<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_NewStudent<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_NewStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NewStudent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_NewStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewStudent(::grpc::ServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_NewStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NewStudent() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_NewStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewStudent(::grpc::ServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNewStudent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_NewStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_NewStudent() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NewStudent(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_NewStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NewStudent(::grpc::ServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NewStudent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NewStudent(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NewStudent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NewStudent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::model::Student, ::protos::Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::model::Student, ::protos::Result>* streamer) {
                       return this->StreamedNewStudent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NewStudent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NewStudent(::grpc::ServerContext* /*context*/, const ::model::Student* /*request*/, ::protos::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNewStudent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::model::Student,::protos::Result>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_NewStudent<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_NewStudent<Service > StreamedService;
};

}  // namespace api


#endif  // GRPC_api_2fstudent_5fapi_2eproto__INCLUDED
