// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/student_api.proto

#include "api/student_api.pb.h"
#include "api/student_api.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace api {

static const char* Service_method_names[] = {
  "/api.Service/NewStudent",
};

std::unique_ptr< Service::Stub> Service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Service::Stub> stub(new Service::Stub(channel));
  return stub;
}

Service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_NewStudent_(Service_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Service::Stub::NewStudent(::grpc::ClientContext* context, const ::model::Student& request, ::protos::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::model::Student, ::protos::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NewStudent_, context, request, response);
}

void Service::Stub::experimental_async::NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::model::Student, ::protos::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewStudent_, context, request, response, std::move(f));
}

void Service::Stub::experimental_async::NewStudent(::grpc::ClientContext* context, const ::model::Student* request, ::protos::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewStudent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protos::Result>* Service::Stub::PrepareAsyncNewStudentRaw(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protos::Result, ::model::Student, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NewStudent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protos::Result>* Service::Stub::AsyncNewStudentRaw(::grpc::ClientContext* context, const ::model::Student& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNewStudentRaw(context, request, cq);
  result->StartCall();
  return result;
}

Service::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Service_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Service::Service, ::model::Student, ::protos::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::model::Student* req,
             ::protos::Result* resp) {
               return service->NewStudent(ctx, req, resp);
             }, this)));
}

Service::Service::~Service() {
}

::grpc::Status Service::Service::NewStudent(::grpc::ServerContext* context, const ::model::Student* request, ::protos::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace api

